### ISSUE TITLE
Null Reference issue

### ISSUE THREAD

**Issue by Anuuviem** [blaxxun-boop/Ranching#5]
I will spontaneously get the following issue. I do have professions installed along with all the other skills added. I did not have ranching selected as one of my professions. Another player on the server does have it selected and has not yet had this issue.

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Component.GetComponent[T] () (at <50b18efe22344b9eb3b7d77b08ea287f>:0)
Ranching.Ranching+SetTamingFlag.Prefix (MonsterAI __instance) (at <f73f87488d254aadaf02abba773ca2f2>:0)
(wrapper dynamic-method) MonsterAI.DMD<MonsterAI::UpdateAI>(MonsterAI,single)
MonoUpdaters.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

This is the error after I return to the main screen. I do not know if it is because of the above error but I will post it here as they seem to be linked.

[Error  : Unity Log] NullReferenceException
Stack trace:
UnityEngine.Animator.GetCurrentAnimatorStateInfo (System.Int32 layerIndex) (at <980e8bfbe08647489fda3619f09eeea6>:0)
Character.UpdateCachedAnimHashes () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Character.GetNextAnimHash () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
Humanoid.InAttack () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)
CreatureLevelControl.CreatureLevelControl+PatchCharacterAnimationSpeed.Prefix (Character ___m_character, UnityEngine.Animator& ___m_animator) (at <bcfbe54da85748d3a3d25047d8dad079>:0)
(wrapper dynamic-method) CharacterAnimEvent.DMD<CharacterAnimEvent::CustomFixedUpdate>(CharacterAnimEvent)
MonoUpdaters.FixedUpdate () (at <dbd2a6fbcde9498cadcacfb37ef883e3>:0)

**Comment by max-fluff** [comment]
+1

**Comment by blaxxun-boop** [comment]
Caused by mods messing up status effects, most likely a mod adding classes to the game.
