### ISSUE TITLE
Ranching skill get massive lvl up from ChebsNecromancy mod minions - ppl told me its fault of Ranching

### ISSUE THREAD

**Issue by arturgaweski** [blaxxun-boop/Ranching#7]
Skeleton and Draugr minions from ChebsNecromancy are detected as tamable creatures and when they die skill lvl of Ranching get massive boost.
Killing few of them got me 59 lvls of Ranching skill. One of mod authors about Taming mod told me that if it doesn't get fixed he will create same Ranching mod, but with compatibility for other mods.
So this problem rest only in your mod and whatever there will be new mod used or yours depends if you fix this issue.

**Comment by blaxxun-boop** [comment]
Nope, needs to be fixed in the other mod.
